### ISSUE TITLE
Error:  no implicit conversion of nil into String

### ISSUE THREAD

**Issue by Frozenfire92** [octopress/paginate#18]
When switching from jekyll-paginate to octopress so I can paginate collections I get the following error

``` bash
Configuration file: /home/.../website/_config.yml
       Deprecation: You appear to have pagination turned on, but you haven't included the `jekyll-paginate` gem. Ensure you have `gems: [jekyll-paginate]` in your configuration file.
            Source: /home/.../website
       Destination: /home/.../website/_site
 Incremental build: disabled. Enable with --incremental
      Generating... 
       Deprecation: Collection#reverse should be called on the #docs array directly.
                    Called by /var/lib/gems/2.1.0/gems/octopress-paginate-1.1.2/lib/octopress-paginate.rb:136:in `collection'.
  Liquid Exception: no implicit conversion of nil into String in _tutorials/2016-01-10-welcome-to-jekyll.markdown
jekyll 3.0.1 | Error:  no implicit conversion of nil into String
```

Here is my config file

``` yml
# Blog settings
permalink: /blog/:year/:month/:day/:title
paginate: 6
paginate_path: "/blog/page/:num"

# Tutorial settings
collections:
  - tutorials

# Plugins
gems:
- octopress-paginate
```

Here is my tutorials index file `tutorials/index.html`

``` html

---
layout: page
nav_layout: tutorial
title: Tutorial Index
paginate:
  collection: tutorials
  permalink: /tutorials/:year/:month/:day/:title

---
{% for tutorial in paginator.tutorials %}
        ...
{% endfor %}
```

Then I have markdown files in the folder `_tutorials`

I think this is related to https://github.com/jekyll/jekyll/issues/3929 and https://github.com/octopress/hooks/issues/13

Maybe relevant info

```
Ubuntu 15.10
ruby 2.1.5p273 (2014-11-13) [x86_64-linux-gnu]
jekyll 3.0.1
```
