### ISSUE TITLE
Sort collection by date

### ISSUE THREAD

**Issue by ow** [octopress/paginate#34]
Howdy,

I'm trying to paginate a collection by the date field I've stored in the front matter... is it possible? I tried to reverse the order but it didn't really help either.

```

---
layout: podcast
paginate:
  collection: podcasts
  pagination_dir: posts
  per_page: 6
  permalink: /podcast/:num/
  reversed: true 

---
```
